version: "3.2"

services:
  account_api:
    container_name: 'account_api'
    image: anilena2016/deploy-account_api:latest
    #build:
    #  context: ../minibank_account_api
    #  dockerfile: ./Dockerfile
    environment:
     - ASPNETCORE_URLS=http://+:8082;https://+:44382;
     - ASPNETCORE_Kestrel__Certificates__Default__Path=/App/ssl/certs/cert.crt
     - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/App/ssl/certs/cert.key
    volumes:
      - ./logs/account/:/App/logs
      - ./minibank.crt:/App/ssl/certs/cert.crt
      - ./minibank.key:/App/ssl/certs/cert.key
      #- C:\temp\logs\account:/App/logs
      #- ./cert.crt:/App/ssl/certs/cert.crt
      #- ./cert.key:/App/ssl/certs/cert.key
      - ./root.crt:/App/ssl/root.crt
      - ./appsettings_account.json:/App/appsettings.json
    networks:
      - minibank
    ports:
      - '8082:80'
      - '44382:44382'
        
  client_api:
    container_name: 'client_api'
    image: anilena2016/deploy-client_api:latest
    #build:
    #  context: ../minibank_client_api
    #  dockerfile: ./Dockerfile
    environment:
     - ASPNETCORE_URLS=http://+:8081;https://+:44381;
     - ASPNETCORE_Kestrel__Certificates__Default__Path=/App/ssl/certs/cert.crt
     - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/App/ssl/certs/cert.key
    volumes:
      - ./logs/client/:/App/logs
      - ./minibank.crt:/App/ssl/certs/cert.crt
      - ./minibank.key:/App/ssl/certs/cert.key
      #- C:\temp\logs\client:/App/logs
      #- ./cert.crt:/App/ssl/certs/cert.crt
      #- ./cert.key:/App/ssl/certs/cert.key
      - ./root.crt:/App/ssl/root.crt
      - ./appsettings_client.json:/App/appsettings.json
    networks:
      - minibank
    ports:
      - '8081:80'
      - '44381:44381'
   
  #nginx:
  #  image: nginx:latest
  #  volumes:
  #   - ./nginx.conf:/etc/nginx/nginx.conf
  #   - ./minibank.conf:/etc/nginx/conf.d/minibank.conf
  #  links:
  #   - client_api
  #   - account_api
  #  networks:
  #    - minibank
  #  ports:
  #    - '80:80'
  #    - '9083:9083'
  #    - '9084:9084'
networks:
  minibank: