name: Build Docker Images

on:
  push:
  pull_request:
    branches: [ dev ]

env:
  CLIENT_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/deploy-client_api:${{ github.sha }}
  ACCOUNT_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/deploy-account_api:${{ github.sha }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        #username: anilena2016
        #password:  'dckr_pat_pHRdycwUUB8uusXDO310aPTBOrw'
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} 

    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Image Client-Api
      uses: docker/build-push-action@v3
      with:
        context: ./minibank_client_api
        file: ./minibank_client_api/Dockerfile
        push: true
        tags: ${{ env.CLIENT_IMAGE }}

    - name: Build Image Account-Api
      uses: docker/build-push-action@v3
      with:
        context: ./minibank_account_api
        file: ./minibank_account_api/Dockerfile
        push: true
        tags: ${{ env.ACCOUNT_IMAGE }}

