name: build

on:
  push:
  pull_request:
    branches: [ dev ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOCKER_HUB_USERNAME: 'anilena2016@gmail.com'
  DOCKER_HUB_ACCESS_TOKEN: 'anilena.12345'
  BACKEND_IMAGE: anilena2016/deploy-client_api:${{ github.sha }}

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ env.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Backend
      uses: docker/build-push-action@v3
      with:
        context: ./minibank_client_api
        file: ./depoly/Dockerfile
        push: true
        tags: ${{ env.BACKEND_IMAGE }}
