name: Docker

on:
  push:
  pull_request:
    branches: [ dev ]
    #paths:
    #- '**.cs'
    #- '**.csproj'

env:
  BACKEND_IMAGE: anilena2016/deploy-client_api:${{ github.sha }}

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{secret.DOCKER_HUB_USERNAME}}
        password: 'dckr_pat_pHRdycwUUB8uusXDO310aPTBOrw'
    
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2

    - name : Get Path
      run: | 
        echo $path
    
    #- name: Build Backend
    #  uses: docker/build-push-action@v3
    #  with:
    #    context: minibank_client_api
    #    file: depoly\Dockerfile
    #    push: true
    #    tags: ${{ env.BACKEND_IMAGE }}
